### ISSUE TITLE
Arm builds fail

### ISSUE THREAD

**Issue by DAP-DarkneSS** [MaartenBaert/ssr#30]
https://pmbs.links2linux.de/package/live_build_log?arch=armv7l&package=simplescreenrecorder&project=Multimedia&repository=openSUSE_12.3_ARM

[  522s] In file included from elfhacks.c:20:0:
[  522s] elfhacks.h:56:4: error: #error neither __elf32 nor __elf64 is defined
[  522s] elfhacks.c:34:37: error: unknown type name 'ElfW_Sword'
[  522s] elfhacks.c:422:37: error: unknown type name 'ElfW_Sword'
[  522s] elfhacks.c: In function 'eh_set_rela_plt':
[  522s] elfhacks.c:456:2: warning: implicit declaration of function 'eh_find_next_dyn' [-Wimplicit-function-declaration]
[  522s] elfhacks.c:460:3: warning: implicit declaration of function 'ELFW_R_SYM' [-Wimplicit-function-declaration]
[  522s] make[2]: **\* [libssr_glinject_la-elfhacks.lo] Error 1
[  522s] make[2]: **\* Waiting for unfinished jobs....
[  522s] In file included from Hook.cpp:13:0:
[  522s] elfhacks.h:56:4: error: #error neither __elf32 nor __elf64 is defined
[  523s] make[2]: **\* [libssr_glinject_la-Hook.lo] Error 1

https://pmbs.links2linux.de/package/live_build_log?arch=armv6l&package=simplescreenrecorder&project=Multimedia&repository=openSUSE_Factory_ARM

[  720s] In file included from elfhacks.c:20:0:
[  720s] elfhacks.h:56:4: error: #error neither __elf32 nor __elf64 is defined
[  720s]  #  error neither __elf32 nor __elf64 is defined
[  720s]     ^
[  720s] elfhacks.c:34:37: error: unknown type name 'ElfW_Sword'
[  720s]  int eh_find_next_dyn(eh_obj_t _obj, ElfW_Sword tag, int i, ElfW(Dyn) *_next);
[  720s]                                      ^
[  720s] elfhacks.c:422:37: error: unknown type name 'ElfW_Sword'
[  720s]  int eh_find_next_dyn(eh_obj_t _obj, ElfW_Sword tag, int i, ElfW(Dyn) *_next)
[  720s]                                      ^
[  720s] make[2]: **\* [libssr_glinject_la-elfhacks.lo] Error 1

**Comment by glaubitz** [comment]
Hi!

I am currently working on the official Debian package for ssr which I will be uploading to Debian unstable (I'm a DD). I am currently doing test builds on arm64 and ran into the exact same problem:

make[2]: Entering directory '/home/glaubitz/ssr/glinject'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..    -pthread -fPIC -g -O2 -MT libssr_glinject_la-elfhacks.lo -MD -MP -MF .deps/libssr_glinject_la-elfhacks.Tpo -c -o libssr_glinject_la-elfhacks.lo `test -f 'elfhacks.c' || echo './'`elfhacks.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -pthread -fPIC -g -O2 -MT libssr_glinject_la-elfhacks.lo -MD -MP -MF .deps/libssr_glinject_la-elfhacks.Tpo -c elfhacks.c  -fPIC -DPIC -o .libs/libssr_glinject_la-elfhacks.o
In file included from elfhacks.c:20:0:
elfhacks.h:63:3: error: #error neither __elf32 nor __elf64 is defined
 # error neither __elf32 nor __elf64 is defined
   ^
elfhacks.c:34:37: error: unknown type name 'ElfW_Sword'

Am I correct when assuming there hasn't been any development in elfhacks regarding this and OpenGL recording still has to be disabled for non-x86 machines?

I just need to make sure that ssr builds on all architectures supported by Debian which are even more than just ARM and x86.

Adrian

**Comment by MaartenBaert** [comment]
Correct. I don't have enough knowledge about the ELF file format and the loader used on ARM to figure out how to add support for it myself. So for now you have to disable the GLInject library on ARM.

**Comment by iamgreaser** [comment]
I somewhat recently messed around with ARM ELF. From my understanding the only thing that'll be different is the relocation types, which can be found in section 4.6 of IHI0044E_aaelf.pdf.

Note, this information is for 32-bit ARM. I don't have information for 64-bit ARM, so you'll have to take a stab in the dark for now.

Each entry is two 32-bit words. The first 32 bits is an address. The second 32 bits is a packed value, the low 8 bits denote the relocation type, the upper 24 bits denote a parameter.

DT_JMPREL consists of several R_ARM_JUMP_SLOT (22 decimal) entries where the upper 24 bits point to an index in the string table - this will give the name of the function that needs to be imported. When writing the function address to the jump table, write the absolute address.

The number of entries in DT_JMPREL is denoted by DT_PLTRELSZ - the entry contains the size of the JMPREL table in bytes.

Hope that helps.

**Comment by MaartenBaert** [comment]
Thanks. I think I will give it a try when I have some more time. I don't have an ARM device with OpenGL support, but I suppose I could test the ElfHacks modifications on a Raspberry Pi with a simple test program (without OpenGL).

I'm not actually trying to modify the relocation table, LD_PRELOAD already gives my hooks priority over the real functions. Normally I would be able to get the original function addresses through dlsym(RTLD_NEXT), but I also have to hook dlsym itself which makes that impossible. So I use ElfHacks just to find the real dlsym(), after that I just call the real dlsym() to find everything else.

In case anyone wonders why I need to hook dlsym(): some games (e.g. Minecraft) dynamically load libGL.so with dlopen() and then get the addresses with dlsym(). Since they specify the library explicitly, they get the real GL functions and not my hooks, so GLInject doesn't work. I solve this by hooking dlsym(), which unfortunately means that I'm also cutting off my own access to the function I need to find the real GL functions.

If there was a 'right' way to find function addresses from a library that didn't involve calling dlsym(), I could use that instead, but I don't know any other way.

**Comment by DAP-DarkneSS** [comment]
Online aarch64/armv6l/armv7l (and ppc* too) builds could be easily maid at  
open(SUSE) build service against any github action. Please request if  
needed.

**Comment by glaubitz** [comment]
Just for the record: I already uploaded ssr to Debian unstable. It's currently waiting in NEW for approval, see: https://ftp-master.debian.org/new/ssr_0.3.3-1.html

**Comment by anders-larsson** [comment]
@glaubitz  I believe @MaartenBaert would prefer that the package name is simplescreenrecorder instead of ssr since naming the package ssr could cause name-conflics. That's what he told me at least when I packaged the application for Gentoo.

**Comment by glaubitz** [comment]
@anders-larsson There is no package ssr in Debian, so I don't see any problem with that. I was pondering whether to use simplescreenrecoder or ssr, but I found the former way too long for a package name which is why I used ssr.

**Comment by MaartenBaert** [comment]
The name 'ssr' would make sense if the executable was actually named 'ssr', but since it is named 'simplescreenrecorder' (which was indeed done to avoid naming conflicts) I think it makes more sense to use the same name for the package. Also, the Ubuntu package is called 'simplescreenrecorder' and it would be nice to have the same command for Debian and Ubuntu (otherwise some people will probably try to run ```apt-get install ssr``` on Ubuntu and ```apt-get install simplescreenrecorder``` on Debian).

It's also likely that Ubuntu will adopt the Debian package at some point, which would make the confusion even worse since Ubuntu users that were already using the 'simplescreenrecorder' package from my PPA would now have two incompatible packages in their package manager. Keeping the same name would allow the package manager to resolve the conflict by simply looking at the version number.

**Comment by glaubitz** [comment]
I just checked the official Ubuntu package archives and there is no package 'simplescreenrecorder' so I don't see your point. PPA archives are not an official part of Ubuntu and it's therefore irrelevant whether conflicting package names exist.

**Comment by MaartenBaert** [comment]
Okay, if you insist. I suppose I will rename the PPA package and turn 'simplescreenrecorder' into a transitional package once Ubuntu picks it up.
