### ISSUE TITLE
Load ssr-glinject lib from outside the LD search path

### ISSUE THREAD

**Issue by darealshinji** [MaartenBaert/ssr#305]
The ssr-glinject library is not a regular shared library but kinda like a plugin. So I've installed it into a private library directory and modified the ssr-glinject script to preload it from there:
`LD_PRELOAD="$LD_PRELOAD:/usr/lib/x86_64-linux-gnu/simplescreenrecorder-lib/libssr-glinject.so" "$@"`

When I start a game with `ssr-glinject mygame` and then start recording with SSR everything works fine. But if I start `mygame` from the SSR GUI it won't work.

OS: Ubuntu 14.04 (64 bit)

**Comment by StripedMonkey** [comment]
Just me teasing here but I would think that troubleshooting this kind of
stuff would be part of doing this. I mean SSR is designed to be used as a
"Plugin" so if you try and make it otherwise by modifying stuff then of
course it probably won't work without more editing.
;)

**Comment by eraggo** [comment]
AFAIK ssr-qlinject -command is supposed to be middle man between the game/openGL content to create easy way to SSR to capture from.
That's why SSR say in openGL capture options that some anti cheat programs might take it as cheating (Valve "maybe")

I haven't got any problems with ssr-glinject yet

**Comment by MaartenBaert** [comment]
There's a good reason why I do it this way. I don't know in advance if the game is 32-bit or 64-bit. In many cases some wrapper script is involved which means it can be any combination of 32-bit and 64-bit programs. That means I need two libraries, so I have two choices:
```
LD_PRELOAD="$LD_PRELOAD:libssr-glinject.so"
```
... which always works fine, or:
```
LD_PRELOAD="$LD_PRELOAD:/distro/specific/library/path/simplescreenrecorder/libssr-glinject-32.so:/distro/specific/library/path/simplescreenrecorder/libssr-glinject-64.so"
```
... which will work, but requires additional code to figure out the correct path, and will repeatedly print warnings because half of the injection attempts will fail due to 32/64 bit mismatch, or:
```
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/distro/specific/library/path/simplescreenrecorder"
LD_PRELOAD="$LD_PRELOAD:libssr-glinject.so"
```
... which will work without warnings (path issues still apply though), but breaks when games try to change LD_LIBRARY_PATH and forget to preserve the original content of the variable (yes, this happens).

What you're suggesting is exactly how the first version of GLInject used to work. The library was stored in ~/.ssr I believe, so you could use GLInject without even installing SSR system-wide. But I moved away from that.

To answer your original question: SSR itself doesn't need the ssr-glinject script, it sets the required environment variables directly (which is easier and less error-prone than using command-line options and a script).
