### ISSUE TITLE
[Feature Request] Automatic openGL window capture

### ISSUE THREAD

**Issue by briansprojects** [MaartenBaert/ssr#307]
I'd really like it if I could have SSR automatically detect and capture the first openGL window that appears that way I don't have to rely on using a hot key to start the recording.

**Comment by StripedMonkey** [comment]
What? "first openGL window that appears... "
I think that I am missing something here,  you need to explain this a bit
better because I cannot imagine a time when SSR should automatically start
recording when a window pops up simply because you don't want to use a
hotkey. and please explain your aversion to hotkeys please.

**Comment by MaartenBaert** [comment]
If your goal is just to record a game from frame one, you can already do that: Enable scaling in SSR and enter the resolution manually. That will allow you to start recording without any OpenGL window. The actual video file will start when the first frame appears.

**Comment by briansprojects** [comment]
>  I cannot imagine a time when SSR should automatically start
recording when a window pops up simply because you don't want to use a
hotkey.

You realize that makes no sense, right? The hotkey feature has no feedback so for example if I'm playing a fps and I am crouching (ctrl) and reloading (r) suddenly I've stopped my recording and I won't know until the recording is finished. I don't like hot key recording.

> you can already do that: Enable scaling

Doing that resulted in a several hundred byte file. OpenGL + Scaling doesn't appear to do anything. I'm using Compiz with Unity so perhaps that's why; everything is OpenGL.

**Comment by briansprojects** [comment]
Allow me to clarify - 

I use SSR to record all of my game play videos. Occasionally the raw video will end up being upwards of 45 minutes. If at any point during my recording I mistakenly press the hotkey, the video is ruined. What's more, occasionally something may go wrong during the setup of a video and SSR fails to capture the window after I press the hotkey. I have no idea this happened because there's **no feedback**.

If SSR could simply wait for an specific window to appear to start recording automatically, it may help fix this issue.

**Comment by StripedMonkey** [comment]
I typically just change the hotkey to something other than a key
combination that is used in the game for instance Alt+P or something that
simply is too out of the way to be a combination that would be used is
instances such as reloading. (Or better yet use the super+alt+shift+p combo
I promise you you will not mess that one up.)
Another thing is that you can enable the recording sounds so that will ping
whenever you start recording or stop it will play a sound, It also has a
separate sound for failed starts. This really removes all your issues
without having to add a new and (My personal opinion) useless feature
unless you want to secretly record whatever someone is doing whenever
something is opened.
There is also a reason why Maarten has a *Preview* button.
I wish I could say to you in the whiniest voice possible *"You realize this
makes no sense right?" (*O.K I know that at this point I am being rude and
obnoxious but hey he started it) ;)

**Comment by briansprojects** [comment]
> There is also a reason why Maarten has a *Preview* button.

There must be some kind of disconnect because the preview feature has **nothing** do to with any of this.

Using this video as an example - https://www.youtube.com/watch?v=ohg3KTE6IOM&list=UUXa6sE6cKXcQ97vI0Emn1XA

To prepare to record this video I had to press ctrl r and simply *hope* that the video started recording. The final cut was a 16 minute video but the raw footage was something like 30 minutes and I had to record it twice because the first time, even though I pressed ctrl r, something went wrong and it didn't begin recording.

**Comment by MaartenBaert** [comment]
Like StripedMonkey suggest, you should really change the hotkey to something else, like Ctrl+P, and enable sound notifications. This should solve the issue.

OpenGL recording + scaling should work fine, SSR will delay the recording until the game is actually opened. You have to start the game with ssr-glinject of course, otherwise SSR can't see it.

**Comment by StripedMonkey** [comment]
Like I said sound notifications should solve the Schrodinger's cat problem
and the preview button allows you to know if your settings work so that you
can see that "Oh, the sound isn't working" or "Oh, It isn't recording
anything"
Please read the comment thoroughly otherwise you might miss something. ;)

**Comment by briansprojects** [comment]
> you should really change the hotkey to something else

I'll close the request and do that for now.

> Please read the comment thoroughly otherwise you might miss something. ;)

Do Maarten a favor and stop replying to issues. You're not helping anyone by being an asshole in a community project.

**Comment by ubuntuaddicted** [comment]
Can't we all get along? ;) Open source projects are great and as a mini community we all should be weary of making comments like you did.

**Comment by StripedMonkey** [comment]
Yes we can get along, Admittedly I was making a bit of fun of this guy but
I honestly don't understand him. He says that the reason why he wants this
feature is because he does not know if the hot-keys actually work until
after he records but he refuses to acknowledge the existence of audio
notifications and the fact that his idea will not actually change that.
(Meaning this still runs the risk of not actually recording whatever) Then
he explains that he doesn't want to use hot-keys because he has *No
feedback* (Despite the fact that recording from the start of the game does
not change this fact) and that maarten and I both said that he can use
sound notifications. He also explains that he doesn't want to use them
because the default (And rather poorly placed for gaming) hot-key is
ctrl+r. I also tell him that using the preview button will solve the issue
of not knowing if he set up the container and audio correctly.
The only reason I could possibly think of using this feature is to secretly
record something without someone knowing. I teased him because he was
insulting me and because he is obviously being something that I shouldn't
say without getting him more angry.

On Mon, Feb 16, 2015 at 8:58 AM, Ubu the Tech Guru <notifications@github.com

**Comment by briansprojects** [comment]
> The only reason I could possibly think of using this feature is to secretly
record something without someone knowing.

If you took a second to educate yourself instead of ignorantly typing the first thing that comes into your head you'd realize how stupid this sounds. Perhaps you could take a moment to visit my [YouTube channel](https://www.youtube.com/user/EtherealGaming1) or my [website] (http://briansprojects.net/). I'd really appreciate it if you not say or insinuate things that not only aren't true but that you have no proof of. Why not try actually contributing to the open source community as a whole instead of showing the community and everyone else what an ignorant troll you are with responses like these -

> I teased him because he was
insulting me and because he is obviously being something that I shouldn't
say without getting him more angry.

**Comment by MaartenBaert** [comment]
Do you two realize that I get an email for every comment posted here? I have better things to do ...
