### ISSUE TITLE
Want another GUI.

### ISSUE THREAD

**Issue by caoli5288** [MaartenBaert/ssr#334]
**First is the about page is extremely inefficient.**
In General, it is desirable to select a region and then immediately start recording.
Somethings like set video, audio, output folder,etc are not need to be changed frequently.
**Why do I have to press the 3 "next" to start recording???**
Maybe you should look at other successful software design
like "record my desktop", "hypercam", "kazam" and others.
I love hypercam design most.
![hypercam](http://www.hyperionics.com/img/hypercam1.jpg)

**Comment by StripedMonkey** [comment]
Well I have good news for you, he is completely revamping the GUI. Its one
of the bigger things he's working on. If you read his site (Or is it here
on Github) he does actually say why he has the format the way it is.

He has said that he is changing the GUI, I don't know what its going to
look like though, he hasn't said that yet as far as I know. The reason he
gave was because SSR is beginning to have too many feautres for the current
layout.

**Comment by MaartenBaert** [comment]
Correct. The new GUI will most likely be similar to the VLC preferences dialog (i.e. multiple pages which can be accessed by selecting a category on the left), plus a sidebar which includes most of the things that are currently located on the 'record' page (record button, info, preview). But don't hold your breath, I haven't even started coding the new GUI yet, there are too many other things that need to be done first.
