### ISSUE TITLE
[Feature Request] - Benchmark

### ISSUE THREAD

**Issue by amarildojr** [MaartenBaert/ssr#377]
Hi,

Would it be possible to add a Benchmarking feature that tests all codecs to see which is the fastest on that particular machine? TrueCrypt does that with it's cyphers: http://www.robo47.net/media/truecrypt/truecrypt-benchmark-i7-620M-aes-ni-10mb.png

Regards,
Amarildo

**Comment by MaartenBaert** [comment]
Codec performance really isn't very machine-dependent. The answer is easy: H.264 is the fastest of the 'normal' codecs, by a wide margin. The only ones that are even faster are special ones like huffyuv and ffvhuff.

There is a benchmark for converter/scaler algorithms, but this is mostly for testing purposes. It was also much easier to implement because the scalers have a very simple API. The codec API is very complex which makes benchmarking harder.
