### ISSUE TITLE
Livestreaming custom codec preset option

### ISSUE THREAD

**Issue by Brottweiler** [MaartenBaert/ssr#381]
Hi, this is just a question regarding Livestreaming and codec.

On the [Live streaming: Codecs](http://www.maartenbaert.be/simplescreenrecorder/live-streaming/#codecs) page it sais this custom codec options: `preset=faster,minrate=2000,maxrate=2000,bufsize=2000,keyint=60`.

Why `preset=faster`? Any reason to not use `preset=ultrafast`?

When I normally record I use ultrafast. I don't care about filesize, just performance, and when livestreaming I noticed `preset=faster` gives 90%-100% CPU usage depending on game (in this case minecraft), while `preset=ultrafast` gives me ~50% CPU usage.

**Comment by iamgreaser** [comment]
They have different constraints:

                                  - ultrafast:
                                    --no-8x8dct --aq-mode 0 --b-adapt 0
                                    --bframes 0 --no-cabac --no-deblock
                                    --no-mbtree --me dia --no-mixed-refs
                                    --partitions none --rc-lookahead 0 --ref 1
                                    --scenecut 0 --subme 0 --trellis 0
                                    --no-weightb --weightp 0
                                  - superfast:
                                    --no-mbtree --me dia --no-mixed-refs
                                    --partitions i8x8,i4x4 --rc-lookahead 0
                                    --ref 1 --subme 1 --trellis 0 --weightp 1
                                  - faster:
                                    --no-mixed-refs --rc-lookahead 20
                                    --ref 2 --subme 4 --weightp 1

I'm not sure what constraints the streaming services rely on, but it seems not even superfast will give the desired result.

You could possibly try adding some of the ultrafast options one-by-one until the streaming service decides to hate you, and then skip those options. This may help: https://sites.google.com/site/linuxencoding/x264-ffmpeg-mapping

**Comment by Brottweiler** [comment]
Are you saying the stream service might refuse to stream if I use ultrafast? When I tested this when streaming with hitbox.tv, cause it supports hidden streams (don't want to spam subscribers with test streams...), it seemed to work using ultrafast.

**Comment by StripedMonkey** [comment]
It may refuse it depending on your settings

**Comment by MaartenBaert** [comment]
As far as I know, everything from medium to ultrafast is supported by most services. You only really get in trouble with the 'slow' presets (because they use more advanced features).

It's a tradeoff between CPU time and network usage. If you have a slow CPU and a fast network connection, you may prefer 'superfast' or 'ultrafast'. If you have a fast CPU and a slow network, you may want to reduce the bitrate without losing too much quality, so in that case 'fast' or 'faster' makes more sense. You also have to take into account that your viewers will have to download at whatever bitrate you use, so if you pick a very high value, it could exclude some viewers with a slow connection.

I thought that 'faster' was a reasonable setting for most users. But if you want to use something else, go ahead.

**Comment by Brottweiler** [comment]
Thanks, that clears it up. I tried using ultrafast with 2000 bitrate, seems to work fine for me.
