### ISSUE TITLE
SSR 0.3.6 install on Debian stretch x86_64 required library missing

### ISSUE THREAD

**Issue by tannx** [MaartenBaert/ssr#418]
SSR version: 0.3.6
OS: Debian testing (stretch x86_64)
NVIDIA Driver Version: 340.96

I've followed the README,md to installed all packages, I ran the ./simple-build-and-install, but it still tell me required library missing. Is same problem with #159  ?

```
checking for gluErrorString in -lGLU... no
configure: error: required library missing
```

Full build configure log here:
[config.log.txt](https://github.com/MaartenBaert/ssr/files/76184/config.log.txt)

**Comment by MaartenBaert** [comment]
You sent in the wrong config.log, that one contains no errors. The error probably happened in the 32-bit part of SSR (build32/config.log). I can guess the reason: you didn't create the 32-bit symlinks as instructed in the README file ;).

**Comment by tannx** [comment]
I see, build32/config.log is here.
[config_32bit.log.txt](https://github.com/MaartenBaert/ssr/files/76194/config_32bit.log.txt)

**Comment by tannx** [comment]
I found this when in the log. I guess this' problem what I get, and I try to create the symlink, but it show that file exists. Is that mean the 32bit-library have some error?
![screenshot from 2016-01-04 18-05-55](https://cloud.githubusercontent.com/assets/5285684/12087451/f5087a44-b30d-11e5-81b2-3b8ec7c5b1b7.png)

**Comment by MaartenBaert** [comment]
There's a typo in your command. The missing library is libGLU.so, not libGL.so.

**Comment by tannx** [comment]
![screenshot from 2016-01-13 03-14-59](https://cloud.githubusercontent.com/assets/5285684/12274030/ecf0888c-b9a3-11e5-8c11-9e6b408531bb.png)

**Comment by MaartenBaert** [comment]
There must still be something wrong with your symlinks, but I need more information to tell you what it is. Please send me:
- the ```config.log``` file in the ```build32``` directory
- the output of ```ls -al /usr/lib/i386-linux-gnu/libGL*```

**Comment by tannx** [comment]
@MaartenBaert 

the config.log file:

[config_log.txt](https://github.com/MaartenBaert/ssr/files/178644/config_log.txt)

and the output of ls -al /usr/lib/i386-linux-gnu/libGL*

![screenshot from 2016-03-18 04-43-16](https://cloud.githubusercontent.com/assets/5285684/13860740/db019676-ecc4-11e5-86da-707bbb21f3e7.png)

**Comment by MaartenBaert** [comment]
Seems like Debian has changed something and now my old fix doesn't work anymore.

In order for compilation to work, the compiler needs to be able to find libGL.so, libGL.so.1, libGLU.so and libGLU.so.1. Normally all of these are symlinks in the /usr/lib/i386-linux-gnu folder which point to the actual libraries (which may be in a different folder, or in the same folder but with a longer version number). It seems that libGL.so.1 is missing in your case, which is really strange because without that library you shouldn't even be able to run 32-bit OpenGL programs in the first place. So either this library is installed somewhere else (try running ```locate libGL.so.1```), or Debian now requires a different package to be installed to get this library.

I don't really recommend randomly linking to libraries in different locations. It's relatively harmless to link libGL.so to libGL.so.1 in the same folder, but it's a different matter when the target library is located somewhere else (which was probably done for a reason).

**Comment by tannx** [comment]
@MaartenBaert 
Very strange. all files could be found, but couldn't created symbolic link.
![screenshot from 2016-03-24 06-17-50](https://cloud.githubusercontent.com/assets/5285684/14002668/547d8308-f188-11e5-80af-6470d6222ed5.png)

**Comment by MaartenBaert** [comment]
You are creating the links in the wrong place. The compiler will only search in a few standard locations, in this case the location you need is /usr/lib/i386-linux-gnu. That's where libGL.so and libGL.so.1 need to be located. Same for libGLU and the other ones.

**Comment by trebmuh** [comment]
SSR entered Debian testing (stretch): https://tracker.debian.org/pkg/simplescreenrecorder
@MaartenBaert : I suggest this thread to be closed as well.
