### ISSUE TITLE
Flashes When Recording

### ISSUE THREAD

**Issue by radams15** [MaartenBaert/ssr#476]
When i record sometimes the background flasheson the video at random intervals in weird shapes, please help

**Comment by MaartenBaert** [comment]
Can you upload an example that shows the problem?

**Comment by StripedMonkey** [comment]
this might be a problem with your graphics card, what are you using?

**Comment by radams15** [comment]
Yes It happens a few times in this video :)
I am using linux and an intel graphics card that installed in the software manager
[Linux Walkthrough.mp4.zip](https://github.com/MaartenBaert/ssr/files/409517/Linux.Walkthrough.mp4.zip)

**Comment by MaartenBaert** [comment]
I've seen similar problems with the GNOME window manager (Mutter), so it makes sense that Cinnamon (which was derived from Mutter AFAIK) is also affected. I believe it has something to do with how they write the final image to the screen. Sometimes SSR will capture an incomplete rendering, and there's really not much I can do to change that. Apparently the other window managers do it differently because they don't have this problem.

You can probably solve this by disabling compositing. I don't think that's an option with Cinnamon though, so then the only alternative is to switch to a different window manager. Any non-compositing window manager should work, and the compositing ones from XFCE and KDE also work fine.

OpenGL recording should still work, but that won't really help you in this case.

**Comment by 1690147** [comment]
I had a similar problem on the driver from Intel.

My environment
OS: RFRemix 24
Kernel: x86_64 Linux 4.9.7-101.fc24.x86_64
DE: KDE5
WM: KWin
CPU: Intel Core i3 CPU 540 @ 3.067GHz
GPU: Mesa DRI Intel(R) Ironlake Desktop

**Solution:**

Instead of the driver from Intel you need to use modesetting.

```
$ cat /etc/X11/xorg.conf.d/00-modesetting.conf
Section "Device"
        Identifier "Intel"
        Driver "modesetting"
EndSection
```

```
$ inxi -G
Graphics:
Card: Intel Core Processor Integrated Graphics Controller
Display Server: Fedora X.org 118.4
driver: modesetting
Resolution: 1920x1080@60.00hz
GLX Renderer: Mesa DRI Intel Ironlake Desktop
GLX Version: 2.1 Mesa 12.0.3
```
