### ISSUE TITLE
SSR Creates a New File When Paused

### ISSUE THREAD

**Issue by octacian** [MaartenBaert/ssr#485]
Whenever I pause mid recording (typically using the hotkey), SSR saves the current file and creates a new one. I could live with it, but the recording time is also reset so I have no idea how long I've been going. The files end with the date, so I assume this is not accidental, but caused by a setting. If so, I have no idea what or where I changed something.

Thanks!

**Comment by MaartenBaert** [comment]
Uncheck 'separate file per segment' :).

**Comment by octacian** [comment]
Thanks! Can't believe I didn't notice that... Figured it was a simple setting I'd accidentally changed, but not **that** simple!

**Comment by MaartenBaert** [comment]
I really don't know what's wrong with that checkbox, but lots of people seem to get confused by it. I get this question (as well as the reverse) all the time. I thought I put it in the most logical place possible: it's right below the file name since the main purpose of the feature is to change the file name.
