### ISSUE TITLE
SSR badly records videos

### ISSUE THREAD

**Issue by Megver83** [MaartenBaert/ssr#489]
I don´t know why this happens. I used SSR long time ago in Xubuntu and it worked fine, but now in Parabola (Arch based, with Plasma 5.7 installed) it starts convulsing (watch the video). What is it? How can I solve it?
https://youtu.be/SNj5ECPIfjo
In the video, I opened windows, moved them, wrote on a terminal, but what you see is what records.
NOTE: I tried with VLC, but it happened the same. Am I missing some software or sth?

**Comment by MaartenBaert** [comment]
Right, so I assume that SSR itself isn't actually flickering like that, it just looks like that in the video.

What I suspect is happening is that the X server is somehow making screenshots of the wrong buffer. Instead of capturing the screen, it is capturing some internal buffer of the window manager. This could be a video driver issue or a bug in the compositor or X server. I don't think I can do anything about this in SSR.

Can you tell me which video card and driver you are using?

The KDE window manager has an option to switch off compositing. The default shortcut is Ctrl+Alt+F12 IIRC. Give that a try. Or alternatively, try to disable page flipping in your video driver.

**Comment by Megver83** [comment]
Definitively isn´t the program. Already tried with RecordMyDesktop and ffmpeg-recorder and the same epileptic attack. 
My video card

`00:02.0 VGA compatible controller: Intel Corporation 4 Series Chipset Integrated Graphics Controller (rev 03) (prog-if 00 [VGA controller])
        Subsystem: Biostar Microtech Int'l Corp Device 3103
        Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B+ ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0
        Interrupt: pin A routed to IRQ 26
        Region 0: Memory at fe400000 (64-bit, non-prefetchable) [size=4M]
        Region 2: Memory at d0000000 (64-bit, prefetchable) [size=256M]
        Region 4: I/O ports at cc00 [size=8]
        [virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: i915
        Kernel modules: i915`
I forgot to say, that I don´t think it´s the video card. I already tested SSR in Trisquel 7 (Ubuntu 14.04 based) with KDE 4 and it worked fine too. Has SSR been tested in Plasma 5.7? Plasma 5.7.4, more specifically.

**Comment by Megver83** [comment]
CONFIRMED: I installed xfce4 and it worked! It´s a problem with KDE 5, not SSR.
https://www.youtube.com/watch?v=Q52xAKkvcgc&feature=youtu.be
