### ISSUE TITLE
Does not record what is actually on screen

### ISSUE THREAD

**Issue by ninjalf2** [MaartenBaert/ssr#490]
On my Arch Linux install using the Enlightenment WM/DE, the screen preview does not show what actually happens on screen and flashes a lot.
For example, the SSR shows 10FPS constant but the preview shows jumping from 0 to 10 repeatedly (seemingly at random).

The cursor is recorded correctly but nothing else is. It shows my WM but when I move windows around or change workspace it just shows the SSR window in fullscreen.

Disabling Compositing effects in E did nothing.

Same issue in Cinnamon.

Using Intel drivers: xf86-video-intel 1:2.99.917+703+g15c5ff1-1
XOrg version: xorg-server 1.18.4-1
Enlightenment: enlightenment-git 0.21.99.21577.g6548fae-1

If any other info is relevant, tell me and I will post it.

**Comment by MaartenBaert** [comment]
Does it look the same as #489? If not, can you upload the video so I can take a look?

Two users have now reported what looks like the same bug in a very short timespan, both using Arch and an Intel GPU. Do you know whether this was caused by a recent update? You could try to downgrade the Intel driver to the previous version to see if that fixes it.

**Comment by ninjalf2** [comment]
It is the EXACT same issue as #489. Sorry, I had not seen the issue was already there as I had expected it would still be an open issue. I see now that the program is not at fault and that it may be a video driver or WM issue.
