### ISSUE TITLE
Any way to recover an incomplete file?

### ISSUE THREAD

**Issue by djsegfault** [MaartenBaert/ssr#496]
Let's say I'm recording something, then I pause it, and try to play the video in VLC.  It won't play, because I need to stop recording. SOMETHING is happening when I stop recording the file to make it a valid playable video file.

If something happens during the recording, like SSR crashes, or the computer reboots, so I didn't get a chance to press stop, I'm left with a completely useless recording file that won't play anywhere.

Is there any way to do whatever happens when you stop the recording, but after the fact, so at least some of the recording would be playable?  Any way to recover any of the recording?

Thanks.

**Comment by StripedMonkey** [comment]
It depends on the container that you used to record it

**Comment by djsegfault** [comment]
Thanks.  Could you expand on that please?

**Comment by MaartenBaert** [comment]
If you use MKV you won't have this problem. MKV files will play even when incomplete, the only thing that won't work is seeking because the length of the video is unknown. However if you use MP4 you will always have this problem because MP4 puts crucial information at the end of the file. There is no practical way to repair incomplete MP4 files.

**Comment by djsegfault** [comment]
Thank you so much! Tested that out and MKV worked.  Thank you for explaining it.  Love SSR.
