### ISSUE TITLE
Build with qt5

### ISSUE THREAD

**Issue by rezso** [MaartenBaert/ssr#498]
I tried to compile the 0.3.6 release with qt 5.5.1:

/usr/lib/qt5/include/QtCore/qglobal.h:1067:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."

After adding -fPIC to qt5 cflags, I can compile ssr. But this is depends on reduce-relocations.

**Comment by MaartenBaert** [comment]
I've seen this before, but I don't remember where. I don't think it's a problem in my code or build system, but a problem with the system configuration. I can't just enable -fPIC everywhere because some systems may need the exact opposite. So adding the flag manually like you did seems like the best solution.
