### ISSUE TITLE
question: are there restrictions placed on recordings created

### ISSUE THREAD

**Issue by markallman** [MaartenBaert/ssr#552]
Hello,

I understand that SSR is distributed under GPL.

Are there any restrictions placed on recordings created using SSR?

thanks, mark

**Comment by QuImUfu** [comment]
Not because of ssr, this is legally not even possible. The only restrictions you recording might have are because what you record/input.
Examples:
If you record a movie playing on you computer the copyright restrictions of the movie recorded apply to the recorded data.
If you record a game like Minecraft, you own the recording and can, because mojang allows you to, licence it yourself relatively freely. This might be different with other games, where the owner restricts whether and how you can distribute the record.

At least this is how i understand it, but i am not a lawyer and have my information mainly from the gpl FAQ:
https://www.gnu.org/licenses/gpl-faq.html#GPLOutput

**Comment by markallman** [comment]
Thank you.

So if I want to create and distribute a video demonstrating how to use a commercial product, I need to have permission from the licence holders of any copyrighted material in the video, understood.

Are there any other restrictions or terms of use that apply to SSR in addition to the GPL?

**Comment by QuImUfu** [comment]
It you record copyrighted material copyright exceptions might apply (eg. [Fair use](https://en.wikipedia.org/wiki/Fair_use) in the US). 

No other restrictions apply, there is nothing special mentioned in the copyright notice or on the website so it is a plain gpl v3 license without anything added.

As i said, i am no lawyer, so everything i said could be wrong.

**Comment by markallman** [comment]
thanks
