### ISSUE TITLE
Installs files with %20 and %29 in their names

### ISSUE THREAD

**Issue by yurivict** [MaartenBaert/ssr#585]
These file names could lose %20, etc:
```
output-profiles/High%20Quality%20Intermediate.conf
output-profiles/Live%20Stream%20%281000kbps%29.conf
output-profiles/Live%20Stream%20%282000kbps%29.conf
output-profiles/Live%20Stream%20%283000kbps%29.conf
```

**Comment by MaartenBaert** [comment]
This creates backward compatibility issues for anyone who has modified these profiles at the user level. If the file names aren't identical, SSR treats them as separate profiles. There is no easy way to fix this without causing more issues. This will have to wait until the settings system is switched from INI to JSON and moved to ~/.config instead of ~/.ssr, at that point I can handle the conversion in a sensible way.
