### ISSUE TITLE
too slow with microcode update

### ISSUE THREAD

**Issue by emullins** [MaartenBaert/ssr#618]
I have a core 2 quad (Q6600) G0 stepping.  I discovered by chance that ssr became slow after applying the microcode update on my Debian system, eg.
```
$ sudo apt-get install intel-microcode iucode-tool
$ sudo reboot
```

I don't claim to understand what the issue is exactly, but ssr is the only package I notice a problem with. Removing the microcode makes ssr work fine, eg.
```
$ sudo apt-get remove intel-microcode iucode-tool
$ sudo reboot
```

Building ssr with/without the microcode update made no difference. Got the same behavior via repository as with building from source.

**Comment by MaartenBaert** [comment]
Can you try to run `simplescreenrecorder --benchmark` with and without the microcode update? This only tests a small part of SSR functionality but it's a start.

What exactly is slow? Is the frame rate lower than it should be? Does this affect both regular recording and OpenGL recording? How significant is the difference?

How old is your motherboard? Intel has released many firmware updates over the years so I'm not sure which specific update is causing the problem. It could be the Spectre patches but this doesn't make a lot of sense. It should only affect kernel code (system calls), but SSR runs mostly in userspace.

**Comment by emullins** [comment]
arg, it's not uploading my benchmark results... 

anyway, it's either not microcode, or not JUST microcode. first thing I did was test it (microcode update was active) and it worked perfectly. I also experienced the slowdown with microcode removed...

symptoms: using the same settings, all screens 1920x1080, 30 frame rate, record cursor, record pulseaudio, mp4, h.264 superfast constant rate factor 26 w/ skipping allowed.  mp3 128kbps.

slow: get FPS in between 13 and 17, and FPS out right around wherever FPS in is.
fast: get FPS in and FPS out at 30.00

it's not useless when slow, but probably only good for something like an instruction video.  wouldn't want to watch games that way.  the interface is sluggish, just moving the mouse around the screen is sluggish (not just in the output file, but also when recording)

I haven't ever recorded OpenGL.  don't know.

10yo mobo.  the spectre updates are just what got me looking at firmwares.  the latest for this mobo is 2010. i am running the latest BIOS.

I've been racking my brain trying to figure out what's different between when I get proper framerates, versus maxing out at 17.  Everything I thought of turned out to not be the case when tested.  I can say that if I need to record something, I can remove the microcode and fart around not very log before it works right, but that's a horrible bug report...

**Comment by MaartenBaert** [comment]
I'm going to assume for now that the microcode is unrelated.

> just moving the mouse around the screen is sluggish

That usually means you don't have enough RAM available. It might be in use by software or by kernel buffers. Try running the `free` command while you are experiencing sluggish mouse movement and post the result here. If cache/buffers are the issue, you may want to adjust `vm.dirty_ratio` and/or `vm.dirty_background_ratio`. If you are using significant amounts of swap even though you still have available memory left, you may want to lower `vm.swappiness`. You can see the current settings by running:
```
sysctl vm.swappiness vm.dirty_ratio vm.dirty_background_ratio
```
My preferred settings (for desktops/laptops):
```
vm.swappiness = 10
vm.dirty_ratio = 5
vm.dirty_background_ratio = 2
```

**Comment by emullins** [comment]
Yeah, I decided months ago it was microcode.  until today I didn't have any reason to think that was wrong.  But clearly it isn't microcode.

It isn't memory either.  during recording, have almost 7 gig free while the mouse is choppy.
Actually.. recording as I type this. The mouse is sluggish when I drag windows around.  Not just wandering around the screen. But there's horrible lag just typing in this box.  This despite my konky reports 15% CPU usage.

**Comment by MaartenBaert** [comment]
'free' memory is not the same as 'available' memory, because of disk caching. In some cases a lot of RAM can be used for buffering data that should be written to disk, especially when dealing with certain types of slow devices (like SD cards). So please double-check that you are not using swap.

If RAM is not the issue and CPU usage is still below 100% of one core, then the problem must be GPU-related. What type of GPU and which driver are you using? In case of NVIDIA, you can see GPU utilization in the settings utility:
![screenshot_2018-01-21_20-46-44](https://user-images.githubusercontent.com/829608/35198274-72ae5870-feec-11e7-9ef3-beaedd5564b1.png)
Pay attention to GPU utilization and PCIe bandwidth utilization. Both of these can easily cause sluggish behavior because GPUs are non-preemptive (i.e. bad at multitasking).

**Comment by emullins** [comment]
Ok.  funny you should mention that.  I was about to ask if it could be Video Card related.  I am running an ancient PCIE1.1 GT 7300 with nouveau driver.  Unfortunately, I cannot run binary drivers, as the latest ones from nvidia do not work with current versions of xorg/mesa/whatever.  i could go back to earlier distros, i suppose to check out binary driver behavior.

I don't know why this would be sporadic though.  It is on my agenda to update cards specifically so I can run a binary driver.  (OT, this will allow me to eliminate my win7 partition)

**Comment by MaartenBaert** [comment]
Nouveau performance is notoriously bad because NVIDIA doesn't provide any documentation to the developers, so there are a lot of missing features (most notably changing the clock frequency to something other that the minimum). Combined with the ancient PCIE interface (limited bandwidth) I'm not surprised that the performance is bad. I would guess that the problem is caused by some other application which is using a lot of PCIE bandwidth.

For some reason, recording consumes a lot of PCIE bandwidth - much more than displaying a video of the same resolution and frame rate. On my machine (PCIE 3.0, 16 lanes) it takes up 15% of the bandwidth to record at 1920x1080 at 60 fps. In theory the bandwidth is 15.75 GB/s, so 15% corresponds to about 2.4 GB/s. In reality a 1920x1080 video at 60 fps with 32 bits per pixel requires only 0.5 GB/s. This matches the bandwidth usage I see during playback, but for some reason the bandwidth usage is 5 times higher during capture of the exact same data. This is true both for regular X11 recording as well as OpenGL recording. I have no clue why this is happening, because PCIE is supposed to be symmetrical (upload and download bandwidth are the same). OpenCL and CUDA seem to be able to use the full bandwidth in both directions.

For what it's worth, AMD and Intel GPUs don't seem to be affected by this issue. Only NVIDIA. I'm starting to suspect that this is an artificial restriction.

In your case, the available bandwidth is only 2 GB/s. You are recording at 30 fps, so you would need about 1.2 GB/s assuming your card is also affected by the inexplicable 5x bandwidth multiplication. So SSR alone is already using 60% of your bandwidth (assuming the Nouveau driver is equally efficient as the binary driver, which is probably not true). Also, AFAIK these GPUs can't transfer data and render graphics at the same time, so while you are running SSR your rendering capacity is also reduced to 40% of the original value. If some other application starts using the GPU too, you could be in trouble.

**Comment by emullins** [comment]
it's clearly not microcode, so you can close this.  I'd like to figure out the issue, but clearly I can get it working by fiddling with it if needed-- just wish I know what was different.

I'll close by illustrating the problem.  the 1st video I ran immediately after reading your latest reply.  the 2nd video, I did nothing but reboot the machine and record.

The sluggishness only occurs while recording.  Watching the conky output is slightly revealing... nowhere in the 2nd recording did the CPU go above 30%... while the first recording, all the compression work was clear... approaching 75% like you'd expect.

Anyway, sorry I can't pin down the cause.

test1: https://youtu.be/N4EWjEInvU4

test2: https://youtu.be/xKaXX71HRWU

[btw, after running test2, I ran each of the programs illustrated, no slowdowns.  whatever is going on only manifests when running ssr]

**Comment by emullins** [comment]
maybe it's just something dumb like nouveau not always initializing the card perfectly.  or maybe a leaky capacitor on the card itself...  it's 10 years old though i guess that would show up outside ssr... i dunno
