### ISSUE TITLE
Useless file on application or system crash, any ideas?

### ISSUE THREAD

**Issue by pascalwhoop** [MaartenBaert/ssr#654]
Hi,
first of all, thanks for this tool. It's perfect! 
Sometimes I record over the span of several sessions. When my PC is in suspend mode, it sometimes doesn't wake up anymore. That's not SSRs fault of course. But when for whatever reason (memory lock, system crash, app crash etc), the file hasn't been completed in SSR, it's just colorful noise. I have a 6GB large file right now that's just noise because my system crashed on my this morning. Thats about 5h worth of recordings gone. Any ideas how to recover them?

Maybe it would also be possible to write the files in a way that they are playable/usable even if the file wasn't properly closed. I know little about mp4 and codecs so I don't know what works how. But afaik, the file may just play even if it is not successfully finished right? When downloading a mp4 file from the browser it may be played even though the download has not completed. Same for a torrent download where it just skipps the missing parts.

Thanks 
Pascal

**Comment by QuImUfu** [comment]
mp4 contains metadata that tells the player what kind of video is stored in the file.
That metadata gets saved after the video file is finished, because some of the data gets available then. (before that no one knows e.g. how long the video will be.) you could try fixing the file e.g. with https://github.com/ponchio/untrunc by creating another, valid file with exactly the same settings and then using the program (it takes the metadata of that correct file and copies it into the corrupted file)

if you want to make sure the mp4 is playable even when ffmpeg crashes/gets crashed, you can pass ffmpeg options to make the mp4 streamable. These are disabled by default because they are slower and incompatible with some players.
https://www.ffmpeg.org/ffmpeg-formats.html#Options-8
contains info about that.

A much simpler solution would be using the matroska (mkv) container that supports streaming anyway and produces files that are readable even when ffmpeg crashes/gets crashed.

**Comment by pascalwhoop** [comment]
@QuImUfu thanks! Using mkv instead of mp4 should be a valid approach when crashing is a possibility. I'm splitting audio/video after recording anyways for audio improvement and then merge them back together before upload. So 
mkv->mp4/mp3->edit-pipeline->mp4->upload
would work for me. 
I'll close this, I think the mkv alternative is enough, implementing a whole "ssr has crashed, let's try and rescue what you lost" process seems unnecessary
