### ISSUE TITLE
Any chance you will support flatpak packaging?

### ISSUE THREAD

**Issue by emcampinline** [MaartenBaert/ssr#666]

**Comment by MaartenBaert** [comment]
I'm currently not interested in this. I will leave packaging to distro maintainers.

**Comment by alex285** [comment]
hello, I want just to give a short feedback; SSR was my favorite screencasting program, but i had to switch to OBS Studio almost 2 years now, even if it gets annoying for recording lots small clips (you cant even cancel a recording), just because it was available as Flatpak;

im leaving this now, because i just searched again if SSR was on Flathub; just feedback, nothing more! thanks!

**Comment by MaartenBaert** [comment]
Can you explain why you can't just install the package the usual way? Does your distribution not provide an SSR package?

**Comment by alex285** [comment]
Hello Maarten,
the original reason was because I was using Fedora Silverblue that we can't really install "RPMs", or it is a bad practice anyway; however nowadays I'm trying to go fully Flatpak, because it is very convenient both on updates, and specially on system upgrades, etc Fedora 32 -> Fedora 33; no dependencies issues, plus everything is always updated are easy to uninstall etc

Im not sure about the OpenGL capture, but considering the FFMPEG, OBS Studio includes it on the bundle:  https://github.com/flathub/com.obsproject.Studio/blob/master/com.obsproject.Studio.json#L102 (plus there is the FFMPEG runtime too)

I could try make an initial Flatpak build for you if you want, but I won't be able to maintain it; however if you want to keep it (and if all works -apart the OpenGL), it is not really lots of work

**Comment by MaartenBaert** [comment]
AFAIK OBS bundles the codecs they need with the software. On Windows this is pretty much the only option. I would prefer to avoid that though since it leads to a lot of bloat when every application includes a full copy of every library it uses. But if you really prefer that approach, you could add ffmpeg with the most important codecs to the flatpak.

If you want to give it a try, go ahead, this is what I used:
```
{
	"app-id": "be.maartenbaert.SimpleScreenRecorder",
	"runtime": "org.kde.Platform",
	"runtime-version": "5.12",
	"sdk": "org.kde.Sdk",
	"command": "simplescreenrecorder",
	"rename-desktop-file": "simplescreenrecorder.desktop",
	"modules": [
		{
			"name": "simplescreenrecorder",
			"buildsystem": "cmake",
			"config-opts": ["-DWITH_QT5=TRUE", "-DWITH_JACK=FALSE", "-DWITH_OPENGL_RECORDING=FALSE", "-DWITH_GLINJECT=FALSE"],
			"sources": [
				{
					"type": "archive",
					"url": "https://github.com/MaartenBaert/ssr/archive/0.4.2.tar.gz",
					"sha256": "a6da4979c7c3f402ea93e43f1c55e289cdcc69653a1a128e32e8bd59481b2511"
				}
			]
		}
	],
	"finish-args": [
		"--device=all",
		"--filesystem=host",
		"--share=ipc",
		"--socket=pulseaudio",
		"--socket=x11"
	]
}
```
If you can get it to work then I don't mind maintaining it.
