### ISSUE TITLE
Opengl recording on Aarch64 question?

### ISSUE THREAD

**Issue by Askmewho** [MaartenBaert/ssr#726]
Hi! Normal encoding its working great, but opengl would be better. I am running panfrost driver on a mali t860mp4 rk3399 sbc. It has for now desktop gl 2.1, but are expected desktop 3.x profile on the near future, but as you told on documentation there is no arm/arm64 support of elf hacks for gl injection. What are they, and would be difficut to be supported on the future? Thanks as always

**Comment by MaartenBaert** [comment]
It refers to these files:
https://github.com/MaartenBaert/ssr/blob/master/glinject/elfhacks.h
https://github.com/MaartenBaert/ssr/blob/master/glinject/elfhacks.c

They parse the ELF files in memory in order to extract information about the addresses of certain functions within system libraries. However since the ELF format is somewhat different for every architecture, the code only supports x86 and x86_64. In order to make it work on ARM you probably only need to set the correct size/offset of some fields, in fact the settings for x86 may work fine for ARM, I've never actually tried it.

If you want to test it, try compiling with `CPPFLAGS=-D__elf32` or `CPPFLAGS=-D__elf64` and see what happens.

**Comment by Askmewho** [comment]
Ohhh,thanks! Right now this program means a lot to me because i am testing opengl drivers from mesa, and even on cpu its doing a great job with some skiping frames here and there. I will try that that flags!

**Comment by MaartenBaert** [comment]
That's an unrelated qt bug, try this workaround:
https://github.com/MaartenBaert/ssr/issues/615#issuecomment-364319248

**Comment by Askmewho** [comment]
yeah, solved on qt5. I will se how it performs, or if it works at all, but at least it finishes. thanks!
