### ISSUE TITLE
"You are using a non-X11 window system" when I'm certainly do (regression?)

### ISSUE THREAD

**Issue by SuperPrower** [MaartenBaert/ssr#781]
My environment is a standalone Window Manager (i3 in this case), and I don't use a Display Manager, like GDM or LightDM, i.e. I start my session via `startx` command. However, previously I was able to use SSR as normal. I use SSR version 0.4.1-1 from Arch Linux Repositories, but I also tried Git version from User Repos with same effect.

Brief look at code suggests that https://github.com/MaartenBaert/ssr/commit/10a3b6099c1d2daaee380c4a02a5aef42eeec125 broke that, since `XDG_SESSION_TYPE` for me is `tty` - I believe that is something for me to fix, but nevertheless, why not just use `QX11Info::isPlatformX11` if it's available?

My `simplescreenrecorder --version` output is:
```
SimpleScreenRecorder 0.4.1
Compiled with GCC 9.3.0
Qt: header 5.14.2, lib 5.14.2
libavformat: header 58.29.100, lib 58.29.100
libavcodec: header 58.54.100, lib 58.54.100
libavutil: header 56.31.100, lib 56.31.100
libswscale: header 5.5.100, lib 5.5.100
```

So Qt function would be available.

**Comment by MaartenBaert** [comment]
`QX11Info::isPlatformX11` is not sufficient because it only tells you whether Qt is using its X11 or Wayland backend, it doesn't distinguish between actual X11 and XWayland. XWayland is exactly what causes most of the confusion because almost everything in SSR remains functional except for the recording itself.

IMHO this is a problem with your setup, `XDG_SESSION_TYPE=tty` would imply that you are not using X11 and running the application from a tty. Since you are not using a desktop manager I suppose you should export `XDG_SESSION_TYPE=x11` manually.

**Comment by SuperPrower** [comment]
> `QX11Info::isPlatformX11` is not sufficient because it only tells you whether Qt is using its X11 or Wayland backend, it doesn't distinguish between actual X11 and XWayland

Ah, interesting, thanks for the clarification and the fix!

**Comment by fairyforest** [comment]
Hey Maarten.
I have the same error on Manjaro Gnome 40.4.0, Kernel 5.9.16-1.
I don't understand the solution above, could you be so kind do explain it in more detail?
Thanks, 
Michael

**Comment by MaartenBaert** [comment]
@fairyforest If SSR is working properly then you can ignore the error. In the latest SSR it should not appear.

**Comment by fairyforest** [comment]
Thanks for your answer.

The program works fine, but the record is completely black and shows only the mouse pointer.

6 Sep 2021 00:59:30 Maarten Baert ***@***.***>:

**Comment by MaartenBaert** [comment]
That means you are using Wayland. You should switch to an X11 session, see #431 .
