### ISSUE TITLE
Two mouse cursors are recorded when using the cinnamon magnifying function.

### ISSUE THREAD

**Issue by marzRX** [MaartenBaert/ssr#815]
![two_mouse_cursor](https://user-images.githubusercontent.com/69402777/89719608-0e6df400-da05-11ea-9bef-75c1f67bcd61.png)
I want to use SSR with Linux Mint cinnamon. I have enabled the accessibility magnifier for cinnamon. And when I use the Magnifier during recording, I get two mouse cursors. 

Is there a way to have one cursor?

**Comment by MaartenBaert** [comment]
If you disable 'record cursor' in SSR, does one of the two cursors disappear?

**Comment by marzRX** [comment]
Thanks for the reply. One of the two cursors disappeared.

But then, unless I zoom in, the mouse won't be recorded.
I need a mouse cursor. I want to make something like a video tutorial with desktop zoom.

**Comment by MaartenBaert** [comment]
I don't think I can fix this. Screen capture never captures the cursor because it is handled as a special extra layer by the graphics card, so SSR actually adds it in later. I don't know how Cinnamon implements the magnifier, but if it doesn't use the standard X11 cursor system to show/hide the cursor as needed, then there's really no way for SSR to detect when it is supposed to add a cursor or not.

If you are only using the magnifier to draw attention to specific things in the video, then I would suggest recording normally and adding the zoom effect later in a video editor, instead of using the accessibility magnifier.

**Comment by marzRX** [comment]
Thank you. I will devise how to use SSR. And I will try expanding with video editing software.

I will post if I know how to get the timing when the cinnamon zoom factor is not 1.0. I am new to Linux, so I may not know forever.
