### ISSUE TITLE
Ubuntu Budgie 20.04 how is this possible (see screenshot)?

### ISSUE THREAD

**Issue by zilexa** [MaartenBaert/ssr#836]
SimpleScreenRecorder says my display resolution is 4096x2560, but as you can see it is actually 2560x1600. Is this a bug? I do not want to end up with a HUGE file due to recording in wrong resolution. I have no other displays attached, rebooted my laptop already. 
![Screenshot from 2020-10-27 15-27-18](https://user-images.githubusercontent.com/3430004/97315442-03d73400-1869-11eb-8ed3-4d5df712fa41.png)

**Comment by zilexa** [comment]
Solved by changing resolution while keeping the application open.

**Comment by MaartenBaert** [comment]
This is very strange, I think you've found a bug in the way Qt calculates the screen resolution. Can you please post the version information from the 'about' dialog (including Qt version)? Also, you say that you've solved the problem, but is the solution actually persistent? Or do you have to redo it every time you restart SSR?

If you are using a reasonably up-to-date version of SSR, then the actual backend code that handles the recording does not depend on Qt for calculating resolutions, so you can always choose 'record a fixed rectangle' and then enter the correct width and height (in physical pixels) manually.

Because of a limitation of the Qt API, Qt will always adjust the reported screen resolution by dividing it by the scale factor, so since your resolution is 2560x1600 and you have a scale factor of 1.25, Qt will normally report the resolution as 2048x1280. SSR then tries to undo this by multiplying by the scale factor again, which is far from ideal because it can cause rounding errors, but usually it works okay. I thought I had most of these problems ironed out, but in your case the resolution is apparently multiplied by 2 rather than 1.25, resulting in 4096x2560.

The only way I can stop Qt from doing this is by disabling high-DPI support entirely, and increase the font size instead. This should solve the problem but has the effect of making the UI elements look different. Still, it may be my only option if problems like this keep popping up.

**Comment by zilexa** [comment]
I actually do not have the issue anymore. Perhaps it was because I had previously connected a monitor (USB-C) to my laptop (which had 2560x1440 resolution) and I disconnected it just before launching SSR for the first time. 
But after changing resolution with SSR running, the issue disappeared and did not return, not even after closing all apps, logging out, logging in again (did not do a reboot anymore). 

I can post the version info later.
