### ISSUE TITLE
Watermark

### ISSUE THREAD

**Issue by Kritiqual** [MaartenBaert/ssr#921]
Can I remove watermark for a recorded video ?

**Comment by Charlie-Ramirez-Animation-Studios-de-MX** [comment]
It seems to me that it is not possible directly in SSR, although you could try it, staying within the field of free/GPL software, with Avidemux.  [MPlayer delogo tool]
**Although that if we must clarify that, it is more an intelligent blur similar to the photoshop patch or correct brush tool,** than a magic elimination since the color and pixel information of the watermark is already in the video _(it would be like trying to erase a coffee/ink stain from a photocopy), but better than nothing,_
and the effect will be more satisfactory depending on the size and colors of both the watermark and the background (plain or lightly textured backgrounds or semitransparent watermarks are easier and more discreet / convincing than a solid multicolored logo or an image of background with many colors or dynamism)

 _-I do not think that is the case; but if the watermark is being generated by SSR you may be using an altered version._
 If you try this method, it would be recommended that you capture with ssr in a format with minimal or no compression (I think the program works better with AVI) [you also have to put the source video in the highest possible quality] in order to try to maintain the highest possible image purity/quality on delogo effect, and then recode with avidemux or with your editor. preference, if the file size is too much
 
 Avidemux – MPlayer delogo http://avidemux.sourceforge.net/    (in Win10 OS there is a version of avidemux in windows store but it is not official and the creators recommend download it from sourceforge)
 
Avidemux Delogo example here: https://cuartogeek.com/tutorial-para-difuminar-un-logo-con-el-programa-avidemux/
 
 If the video is for youtube and you are not bothered by a simple blur effect, you can use the blur effect of the youtube editor once uploaded and that's it

**Comment by Kritiqual** [comment]
So, apparently, I have not much usecase of the app and the logo is not that big problem, closing this issue
