### ISSUE TITLE
Windows blink in final video

### ISSUE THREAD

**Issue by PowaBanga** [MaartenBaert/ssr#923]
Hi
I am on archlinux, with cinnamon, and so, when i record my screen, i have no problem, but when i watch it, it's a nightmare, all windows are blinking !
i make this video to show an example : https://drive.google.com/file/d/1ZvmuS7tOATFNbGU5zzOqYupufwy_RAo5/view?usp=sharing

If anybody can help me to fix that he will have my eternal gratitude !

**Comment by Charlie-Ramirez-Animation-Studios-de-MX** [comment]
_wow it really is strange_

a few things to rule out first: 

- **Recently there have been quite a few updates to the kernels of some distros due to vulnerabilities that were discovered so it would be worthwhile to also see if there are no pending updates for the system**
- Try to update simplescreen, (the current version is 0.4.4, the easiest way to get it is to compile it directly from here on github, it's easy and the instructions on how to do it are at the bottom of the page). repository). [Some people seem to have problems with the version of Snap on some distributions]

- Try to use the different recording modes in rectangle or window or full screen mode (if you use rectangle mode make sure you are not capturing empty areas or going off screen especially on multi-monitor machines)

- adjust the capture fps, especially if they are very high, try lower settings like 60/50-30 (or less) fps.
-it is rare but especially if you have used custom settings first try the default settings, (MKV format with h.264 codec). ratio 23-24.

- if the problem persists it may be a conflict with the linux window composer, try changing it to X11 mode or disable the composer effects in the linux options. in addition try using another desktop such as KDE plasma or gnome, in case it is a cinammon problem that is not solved by disabling the effects of the screen composer (if it were the problem you would have to notify the cinammon team or wait for a next update)

- **[although it seems to me that this is not the case]** if it only happens with firefox (try another browser or disable extensions or windows that are not necessary) - Some games and streaming pages like netflix have DRM's to prevent video from being captured (I don't know if it affects all systems or just to windows and android).  

_weird but not least: If you are using an additional or external display, it is firmly connected (especially on multi-monitor rigs Simplescreen is configured to auto switch input source if signal is lost)

**These are first instructions for common failures, if it still persists, let us know to see what we can do within our reach.** also check if the SSR log (text that appears in the recording window does not show you any failure or error log)

**Comment by mlig212** [comment]
Hi everyone,
(sorry for my Uglish, I'm native French speaker)
I'm on Linux Mint Uma 20.3.
I tested all possibilities with same issues (blinking, 'shearing').
The problem comes from NVIDIA hardware (the videocard). You don't have to try to change preferences and options in the Linux nvidia X Server Settings like 'Allow Flipping' or not, it doesn't change anything. 
The fix is to use a H264 encoder in place of nvidia, known as NVENC in OBS Studio for instance.
Enjoy!
![h264](https://user-images.githubusercontent.com/22004799/186746293-1678a5e2-90c6-4754-8f17-b731e2a7bcd7.png)

Regards
mlig

**Comment by PowaBanga** [comment]
problem was fixed by installing mesa in my case

**Comment by mlig212** [comment]
Sorry impossible to install Mesa with Nvidia already installed. Mesa stays on nvidia # version.

**Comment by mlig212** [comment]
Doesn't work sorry (problem coming from nvidia settings, impossible to find)

**Comment by PowaBanga** [comment]
@mlig212 which are your graphics cards and drivers ?

**Comment by mlig212** [comment]
Nvidia 470.141.03 driver 11.4.
No GeForce Exp (because of Linux ubuntu os system)
Settings uninstalled (worse with)
![cmd = nvidia smi nvidia 470 141 03 driver 11 4](https://user-images.githubusercontent.com/22004799/196690376-d8a58999-39d7-4b43-a8c6-4d17d2faf8e9.png)

**Comment by PowaBanga** [comment]
have you only one graphic card on your computer ? (`lspci -k | grep -EA3 'VGA|3D|Display'`)

**Comment by mlig212** [comment]
I don't thing so
![Screenshot from 2022-10-19 15-17-31](https://user-images.githubusercontent.com/22004799/196702263-f16fb888-9a04-44a5-8493-88dfcf8b4ee1.png)

**Comment by mlig212** [comment]
![github obs screenrec sample](https://user-images.githubusercontent.com/22004799/206875414-8c717aca-6364-44ed-838f-f60b1890bddd.jpg)
Here a sample of what with blink (orange arrows)

**Comment by PowaBanga** [comment]
@mlig212 if you yet have this issue, which is your os ?
I think that i finaly fixed this issue installing a package...

**Comment by PowaBanga** [comment]
I am on archlinux, i think the package was mesa, but not sure at 100% :s

**Comment by mlig212** [comment]
Hey Powa and Creteil,
I'm on Linux Mint Una (20.3)
OBS Studio 25.0.3
FireFox last version so far (11 dec 22)

**Comment by PowaBanga** [comment]
did try to install packages about mesa @mlig212 ?
like mesa-utils or mesa-vulakan-drivers ?

**Comment by mlig212** [comment]
Hi everyone,
With OBS Studio it's possible to capture screen directly from the HMDI source (Red frame, opt & prefs green frame see attached image), and put recording quality to 60fps. Flickering disappears.
![obs hmdi](https://user-images.githubusercontent.com/22004799/216766876-c840f668-dd02-412b-a336-d67c29daa92c.png)

**Comment by PowaBanga** [comment]
@mlig212 did you fixed your issue about you speak early in this thread ? And does your question have anything about this thread ?

**Comment by mlig212** [comment]
Hi Powa 
This is my last post about. You could close the thread.
