### ISSUE TITLE
black screen with xubuntu

### ISSUE THREAD

**Issue by mifads** [MaartenBaert/ssr#931]
When recording I get the sound, but a black screen, even though I am using Xubuntu 21.10 (hence xfce, Xorg) and not the wayland system that seems to cause such problems normally. Help....

**Comment by Charlie-Ramirez-Animation-Studios-de-MX** [comment]
Hi, You've probably already tried this but try configuring xubuntu to use X11 as the graphics manager (I don't remember the exact name of the function but it's the same place where you can choose whether to use wayland). or in the options during screen lock

-a few things to rule out failures:
-Some people are having problems with the Snap version of SSR. try to use the apt repository version or directly update it using the instructions to compile it from here on Github (Current Version is 0.4.3 - 0.4.4)
-if you are using opengl mode make sure it is configured properly since it uses a module that must be injected
-try to use rectangular recording mode or make sure you have correctly selected the monitor you are using (it usually happens that in computers with more than one monitor or connected output these are changed or disabled so SSR captures an empty area)

- Try to use the preview, if the preview shows without problem, you may have some incompatibility with the Codec or format settings (especially if you used custom settings)

If the problem persists, try checking the recording log after a test recording to see if it returns more details. (copy and paste it here, maybe can have help information). 
![image](https://user-images.githubusercontent.com/64709446/149608986-5c0431ff-db23-4eee-af60-1bea1c6e626c.png)
