### ISSUE TITLE
How to record a certain process screen?

### ISSUE THREAD

**Issue by machinexa2** [MaartenBaert/ssr#936]
Lets say I opened zoom but I browser firefox-esr and it records firefox/whatever window I am on. 
![image](https://user-images.githubusercontent.com/60662297/150907048-95a19857-ef10-4ee6-8046-970a7518a5cf.png)
I dont think any of those can do what I am asking or can it??

**Comment by machinexa2** [comment]
I want to record zoom llike its focused fully but also browse firefox at same time

**Comment by Charlie-Ramirez-Animation-Studios-de-MX** [comment]
The simplest way (physically). is to use two monitors to extend the desktop and let Zoom on one monitor and browse on the other (if your pc has a port You can use a TV connected by HDMI or VGA) as an "extra monitor" [don't worry about VGA quality or degradation as it doesn't affect simplescreen]   this way simplescreen only records one monitor and you can do whatever you want on the other (_Of course this will also capture the audio of what you do on the other screen "[wink wink]" so be careful)._ - To avoid this, a separate audio thread / sink can be used, configuring the ALSA server, Jack or Pulse Audio, with the terminal or the "Carla plugin"   Details on: https://www.maartenbaert.be/simplescreenrecorder/recording-game-audio/

- Another option could be to try the recording through Open GL which is based on injecting a library in the program so that Simplescreen obtains the frames before being displayed on the screen, which would be the closest thing to capturing individual processes. however it can be somewhat complicated to try (mostly by trial and error)

the function is mainly intended to be used with steam games, but it would be worth trying with the data from the official page of the project
https://www.maartenbaert.be/simplescreenrecorder/recording-steam-games/

**Comment by machinexa2** [comment]
seems like tough thing to do, anways thanks for help
