### ISSUE TITLE
[archlinux] ssr has been moved to AUR.

### ISSUE THREAD

**Issue by kxxt** [MaartenBaert/ssr#999]
Hi, thanks for this awesome software.

I have noticed that simplescreenrecorder package has been removed from arch linux and moved to AUR.

The web page should be updated: https://www.maartenbaert.be/simplescreenrecorder/#download

**Comment by MaartenBaert** [comment]
I can't find the reason they dropped it - presumably no maintainer? I don't think the package is broken. I've updated the webpage but still hope that some Arch maintainer is willing to pick it up (or otherwise tell me what needs to be fixed to get it back in).

**Comment by kxxt** [comment]
The package isn't broken. I guess they dropped this package because of lack of package maintainer. Many packages are dropped in that cleanup.  It's really a pity.

**Comment by Creteil** [comment]
@MaartenBaert,

I use « ssr » since the very 1st time, and to be honest, at the beginning of 2023, I have searched for any trace of your death (really...).

Your new message enjoy me, and if you don't have time anymore for this project, it's secondary.

As of today, package build properly under latest Ubuntu 22.04 LTS...
